# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adventure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp_range_start', models.IntegerField()),
                ('level', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
